-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jul 07, 2022 at 07:21 AM
-- Server version: 10.4.22-MariaDB
-- PHP Version: 8.1.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `caughtscene`
--

-- --------------------------------------------------------

--
-- Table structure for table `movies-list`
--

CREATE TABLE `movies-list` (
  `movieID` int(100) NOT NULL,
  `Title` varchar(50) NOT NULL,
  `Image` varchar(200) NOT NULL,
  `Director` varchar(50) NOT NULL,
  `Cast` varchar(100) NOT NULL,
  `Genre` varchar(100) NOT NULL,
  `Date` varchar(20) NOT NULL,
  `Story` text NOT NULL,
  `Links` varchar(100) NOT NULL,
  `server` varchar(150) NOT NULL,
  `server2` varchar(150) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `movies-list`
--

INSERT INTO `movies-list` (`movieID`, `Title`, `Image`, `Director`, `Cast`, `Genre`, `Date`, `Story`, `Links`, `server`, `server2`) VALUES
(78, 'Doctor Strange in the Multiverse of Madness', 'https://i.postimg.cc/ydzmvWsd/Doctor-Strange-in-the-Multiverse-of-Madness.webp', 'Sam Raimi', 'Benedict Cumberbatch, Elizabeth Olsen, Chiwetel Ejiofor', 'Action, Adventure, Fantasy', '2022-05-06', 'Doctor Strange teams up with a mysterious teenage girl from his dreams who can travel across multiverses, to battle multiple threats, including other-universe versions of himself, which threaten to wipe out millions across the multiverse. They seek help from Wanda the Scarlet Witch, Wong and others.', 'Doctor-Strange-in-the-Multiverse-of-Madness', 'hJLyQ3gfFRJQ', 'aervs2re9m8e'),
(77, 'Soul', 'https://i.postimg.cc/wvG3sGbw/soul.webp', 'Pete Docter, Kemp Powers', 'Jamie Foxx, Tina Fey, Graham Norton, Rachel House', 'Adventure, Animation, Comedy, Family, Fantasy, Music', '2020-12-25', 'Joe is a middle-school band teacher whose life hasn\'t quite gone the way he expected. His true passion is jazz -- and he\'s good. But when he travels to another realm to help someone find their passion, he soon discovers what it means to have soul.', 'soul', 'GcIFfMa49MrC', 'GcIFfMa49MrC'),
(76, 'The King\'s Man', 'https://i.postimg.cc/Lsbs7ghn/The-Kings-Man.webp', 'Matthew Vaughn', 'Ralph Fiennes, Gemma Arterton, Rhys Ifans', 'Action, Adventure, Thriller', '2021-12-22', 'In the early years of the 20th century, the Kingsman agency is formed to stand against a cabal plotting a war to wipe out millions.', 'The-Kings-Man', 'rYxd8I0UKlGn', '2gj0r4eb9urk'),
(75, 'An Inconvenient Truth', 'https://i.postimg.cc/XqJ9cPZr/An-Inconvenient-Truth.webp', 'Lawrence Bender', 'Al Gore, Billy West, Ronald Reagan, George W. Bush, George H. W. Bush', 'Documentary', '2006-01-24', 'A documentary on Al Gore\'s campaign to create the issue of global warming an accepted problem.', 'An-Inconvenient-Truth', 'sBF6n18eVz5f', '8bkh4r5vqrlk'),
(74, 'The Core', 'https://i.postimg.cc/28BZTbDD/The-Core-2013.webp', 'Jon Amiel', 'Aaron Eckhart, Hilary Swank, Delroy Lindo', 'Action, Adventure, Sci-Fi', '2003-03-27', 'The Earth\'s core has stopped spinning. Disasters are appearing all over the world: Birds acting crazy, powerful thunderstorms, 32 people die within seconds of each other when their pacemakers quit working. Dr. Josh Keyes and his crew of five (total members: 6) go down to the center of the Earth to set off a nuclear device to make the Earth\'s core start spinning again or Mankind will perish.', 'The-Core-2003', 'M68np6JeK1Or', 'sfqz2kkn0pvu'),
(73, 'Back to the Future', 'https://i.postimg.cc/YSK88zFQ/Back-to-the-Future-1985.webp', 'Robert Zemeckis', 'Michael J. Fox, Christopher Lloyd, Lea Thompson', 'Adventure, Comedy, Sci-Fi', '1985-07-02', 'Marty McFly, a typical American teenager of the Eighties, is accidentally sent back to 1955 in a plutonium-powered DeLorean \"time machine\" invented by a slightly mad scientist. During his often hysterical, always amazing trip back in time, Marty must make certain his teenage parents-to-be meet and fall in love - so he can get back to the future.', 'Back-to-the-Future-1985', 'FrQqxwM42Vji', 'vuw0v94cwy6y'),
(72, 'Gravity', 'https://i.postimg.cc/mDk2tCrF/Gravity-2013.webp', 'Alfonso Cuarón', 'Sandra Bullock, George Clooney, Ed Harris', 'Drama, Sci-Fi, Thriller', '2013-10-03', 'Dr. Ryan Stone (Sandra Bullock) is a brilliant medical engineer on her first shuttle mission, with veteran astronaut Matt Kowalski (George Clooney) in command of his last flight before retiring. But on a seemingly routine spacewalk, disaster strikes. The shuttle is destroyed, leaving Stone and Kowalsky completely alone - tethered to nothing but each other and spiraling out into the blackness.', 'Gravity-2013', 'SJo4SQ7ioaSh', 'ttlxzhvetsu0'),
(71, 'Fantastic Voyage', 'https://i.postimg.cc/xCz3DJSL/Fantastic-Voyage.webp', 'Richard Fleischer', 'Stephen Boyd, Raquel Welch, Edmond O\'Brien, Donald Pleasence', 'Adventure, Family, Sci-Fi', '1966-09-23', 'Scientist Jan Benes (Jean Del Val), who knows the secret to keeping soldiers shrunken for an indefinite period, escapes from behind the Iron Curtain with the help of C.I.A. Agent Grant (Stephen Boyd). While being transferred, their motorcade is attacked. Benes strikes his head, causing a blood clot to form in his brain. Grant is ordered to accompany a group of scientists as they are miniaturized. They have one hour to get to Benes\' brain, remove the clot, and get out.', 'Fantastic-Voyage', 'KaQcn63Gvwyr', 'yst81mbizxul'),
(70, 'Spider-Man: No Way Home', 'https://i.postimg.cc/65LwvF3Y/Spider-Man-No-Way-Home.webp', 'Jon Watts', 'Zendaya, Benedict Cumberbatch, Tom Holland', 'Sci-Fi, Adventure, Action', '2021-12-17', 'With Spider-Man\'s identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.', 'Spider-Man-No-Way-Home', 'ArA22Mc0nYkH', '8pdz2y8bew32'),
(69, 'No Time to Die', 'https://i.postimg.cc/9Q9QtGdY/No-Time-to-Die.webp', 'Cary Joji Fukunaga', 'Daniel Craig, Ana de Armas, Rami Malek', 'Action, Adventure, Thriller', '2021-10-08', 'James Bond has left active service. His peace is short-lived when Felix Leiter, an old friend from the CIA, turns up asking for help, leading Bond onto the trail of a mysterious villain armed with dangerous new technology.', 'No-Time-to-Die', 'Xms6Rw0SaMdq', '7aodfzbel6j5'),
(68, 'Eternals', 'https://i.postimg.cc/V6vbGC1x/eternals.webp', 'Marvel Studios', 'Ma Dong-seok, Lia McHugh, Angelina Jolie, Salma Hayek, Richard Madden', 'Adventure, Action, Science Fiction, Drama', '2021-11-03', 'The Eternals are a team of ancient aliens who have been living on Earth in secret for thousands of years. When an unexpected tragedy forces them out of the shadows, they are forced to reunite against mankind’s most ancient enemy, the Deviants.', 'eternals-2021', '6OHWwkvivAnn', '0sc033et0akb'),
(67, 'Army of Thieves', 'https://i.postimg.cc/Qtm055mv/Army-of-Thieves.webp', 'Matthias Schweighöfer', 'Matthias Schweighöfer, Nathalie Emmanuel, Ruby O. Fee', 'Action, Comedy, Crime', '2021-10-29', 'A prequel, set before the events of Army of the Dead, which focuses on German safecracker Ludwig Dieter leading a group of aspiring thieves on a top secret heist during the early stages of the zombie apocalypse.', 'Army-of-Thieves', 'naasiAly938N', 'hb50ps06786g'),
(66, 'Maze Runner: The Scorch Trials', 'https://i.postimg.cc/0QL9pCrJ/Maze-Runner-The-Scorch-Trials.webp', 'Wes Ball', 'Dylan O\'Brien, Kaya Scodelario, Thomas Brodie-Sangster', 'Action, Sci-Fi, Thriller', '2015-09-18', 'The second chapter of the epic \"Maze Runner\" saga. Thomas (Dylan O\'Brien) and his fellow Gladers face their greatest challenge yet: searching for clues about the mysterious and powerful organization known as WCKD. Their journey takes them to the Scorch, a desolate landscape filled with unimaginable obstacles. Teaming up with resistance fighters, the Gladers take on WCKD\'s vastly superior forces and uncover its shocking plans for them all.', 'Maze-Runner-The-Scorch-Trials', 'N5OYJT6I2ckI', 'xc6ys3rawi4a'),
(65, 'The Internship', 'https://i.postimg.cc/T30pCpRH/the-internship-2013.webp', 'Shawn Levy', 'Vince Vaughn, Owen Wilson, Rose Byrne', 'Comedy', '2013-06-06', 'Billy (Vince Vaughn) and Nick (Owen Wilson) are salesmen whose careers have been torpedoed by the digital world. Trying to prove they are not obsolete, they defy the odds by talking their way into a coveted internship at Google, along with a battalion of brilliant college students. But, gaining entrance to this utopia is only half the battle. Now they must compete with a group of the nation\'s most elite, tech-savvy geniuses to prove that necessity really is the mother of re-invention.', 'the-internship-2013', 'PxFElEqXkaMV', 'jyjk8ua71o0m'),
(64, 'Pokemon The Movie:Secrets Of The Jungle', 'https://i.postimg.cc/d3xy6DBK/Pokemon-The-Movie-Secrets-Of-The-Jungle.webp', 'Tetsuo Yajima', 'Sarah Natochenny, Kimlinh Tran, Edward Bosco', 'Action, Adventure, Animation', '2021-10-08', 'The story of Koko, a young boy raised by Pokémon, and the creation of a new bond between humans and Pokémon.', 'Pokemon-The-Movie-Secrets-Of-The-Jungle', 'QthmIJd8pLen', 'xadtquwso7u7'),
(63, 'Captain America: The First Avenger', 'https://i.postimg.cc/t4WgbBWK/Captain-America-The-First-Avenger.webp', 'Joe Johnston', 'Chris Evans, Hugo Weaving, Samuel L. Jackson', 'Action, Adventure, Sci-Fi', '2011-07-21', 't is 1942, America has entered World War II, and sickly but determined Steve Rogers is frustrated at being rejected yet again for military service. Everything changes when Dr. Erskine recruits him for the secret Project Rebirth. Proving his extraordinary courage, wits and conscience, Rogers undergoes the experiment and his weak body is suddenly enhanced into the maximum human potential.', 'Captain-America-The-First-Avenger', 'la76xAOCSgjv', 'km4gjqhkwr90'),
(62, 'Injustice', 'https://i.postimg.cc/5tdp5T0B/Injustice-2021.webp', 'Matt Peters', 'Gillian Jacobs, Laura Bailey, Anson Mount', 'Action, Adventure, Animation', '2021-10-19', 'On an alternate Earth, the Joker tricks Superman into killing Lois Lane, which causes a rampage in the hero. Superman decides to take control of Earth, Batman and his allies will have to attempt to stop him.', 'Injustice-2021', 'cb9KqfLrkgDt', 'els9g19vcq1i'),
(61, 'Dark Web: Descent Into Hell', 'https://i.postimg.cc/ZKhBHb7z/Dark-Web-Descent-Into-Hell.webp', 'Diego Savignano', 'Lucas Sarquiz, Jimena Frontera, Chucho Fernández', 'Horror', '2021-09-17', 'The Dark Web is the large part of the Internet that is inaccessible to conventional search engines. Experts estimate that search engines crawl and index less than 1% of all the content that can be accessed over the Internet. A young YouTuber, \"Ludovico 122\", will try to reach the eighth level of the Dark Web, penetrating the deepest and unknown part of the internet while he films the experience for his audience. But he is not prepared for a horrible surprise that will change his life.', 'Dark-Web-Descent-Into-Hell', 'CiqKiKO61kMk', 'rg3incuszbob'),
(60, 'Sonic the Hedgehog', 'https://i.postimg.cc/NffD9P0b/Sonic-the-Hedgehog.webp', 'Jeff Fowler', 'Ben Schwartz, James Marsden, Jim Carrey, Tika Sumpter', 'Action, Adventure, Comedy, Family, Sci-Fi', '2020-02-12', 'Based on the global blockbuster videogame franchise from Sega, SONIC THE HEDGEHOG tells the story of the world\'s speediest hedgehog as he embraces his new home on Earth.', 'Sonic-the-Hedgehog', 'WBG1ntjWizhE', 'wv1tj6kfkivx'),
(59, 'Venom: Let There Be Carnage', 'https://i.postimg.cc/0NSKWmrY/Venom-Let-There-Be-Carnage.webp', 'Andy Serkis', 'J.K. Simmons, Michelle Williams, Tom Holland, Tom Hardy', 'Science Fiction, Action', '2021-09-15', 'After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.', 'Venom-Let-There-Be-Carnage', 'Pn79qxisBXPz', 'rl36mksbyfy0	'),
(58, 'Shang-Chi and the Legend of the Ten Rings', 'https://i.postimg.cc/mD1X6cR7/Shang-Chi-and-the-Legend-of-the-Ten-Rings.webp', 'Destin Daniel Cretton', 'Tony Chiu Wai Leung, Simu Liu, Awkwafina', 'Adventure, Action, Fantasy', '2021-09-03', 'Shang-Chi, the master of weaponry-based Kung Fu, is forced to confront his past after being drawn into the Ten Rings organization.', 'Shang-Chi-and-the-Legend-of-the-Ten-Rings', 'rkTZEhm660Hv', 'hse2y2ey75yo'),
(57, 'The Addams Family 2', 'https://i.postimg.cc/nzmpxhpt/The-Addams-Family-2.webp', 'Greg Tiernan, Conrad Vernon', 'Oscar Isaac, Charlize Theron, Chloë Grace Moretz', 'Adventure, Animation, Comedy', '2021-10-01', 'The Addams get tangled up in more wacky adventures and find themselves involved in hilarious run-ins with all sorts of unsuspecting characters. Sequel to the 2019 animated film, \'The Addams Family\'.', 'The-Addams-Family-2', '5MEkNVe0odGI', 'l5qxd5mtnz08'),
(56, 'Scouts Guide to the Zombie Apocalypse', 'https://i.postimg.cc/KcNNmpXH/Scouts-Guide-to-the-Zombie-Apocalypse.webp', 'Christopher Landon', 'Tye Sheridan, Logan Miller, Joey Morgan', 'Action, Comedy, Horror', '2015-10-30', 'A reckless janitor accidentally releases a zombie from a laboratory of research. Meanwhile, the teenagers scouts Ben Goudy and Carter Grant decide to camp for the last time since they are too old to be scouts. The problem is that they do not want to harm the feelings of their friend Augie Foster and the Scout Leader Rogers.', 'Scouts-Guide-to-the-Zombie-Apocalypse', 'l4BwkxBVtLsV', 'u3vav6tg6rc1'),
(55, 'Coach Carter', 'https://i.postimg.cc/tTDxx5yz/coach-carter-2005.webp', 'Thomas Carter', 'Samuel L. Jackson, Rick Gonzalez, Robert Ri\'chard', 'Biography, Drama, Sport', '2005-01-14', 'In 1999, Ken Carter accepts the job of basketball coach for his old high school in a poor area of Richmond, CA. As much dismayed by the poor attitudes of his players as well as their dismal play performance, Carter sets about to change both. He imposes a strict regime typified in written contracts that demand respectful behavior, a dress code and good grades for players. ', 'coach-carter-2005', '4pclAHulNbSI', 'dy7zyc45ckn9'),
(54, 'My Little Pony: A New Generation', 'https://i.postimg.cc/0QPrkwg1/My-Little-Pony-A-New-Generation.webp', 'Robert Cullen, José Luis Ucha, Mark Fattibene', 'James Marsden, Vanessa Hudgens, Jane Krakowski', 'Adventure, Animation, Comedy', '2021-09-24', 'After the time of the Mane 6, Sunny--a young Earth Pony--and her new Unicorn friend Izzy explore their world and strive to restore Harmony to Equestria.', 'My-Little-Pony-A-New-Generation', '5dJuASGnDtO2', 'rp3c5hgk6e6s'),
(53, 'Confessions of an Invisible Girl', 'https://i.postimg.cc/q79YdJyn/confessions-of-an-invisible-girl-2021.webp', 'Bruno Garotti', 'Stepan Nercessian, Klara Castanho, Juacute, lia Rabello', 'Drama, Comedy', '2021-09-22', 'Tetê doesn\'t feel accepted either at school or at home. When her unemployed parents must move in with her grandparents to their home in Copacabana, in Rio de Janeiro, the 16-year-old girl must start over at a new school. She will try everything not to be bullied again, and maybe make friends and have a social life.', 'confessions-of-an-invisible-girl-2021', 'ysgU74MaMXGp', 'oe9kl68z02h9'),
(52, 'Intrusion', 'https://i.postimg.cc/tRcRfPmm/intrusion-2021.webp', 'Adam Salky', 'Freida Pinto, Logan Marshall-Green, Robert John Burke', 'Drama, Thriller', '2021-09-22', 'A woman moves to a small town with her husband, but is rattled when she is targeted for a home invasion.', 'intrusion-2021', 'ErTgWBlGdTCM', 'zffd02q9x4cu'),
(51, 'As the Gods Will', 'https://i.postimg.cc/LsXg5GjB/As-the-Gods-Will-2014.webp', 'Takashi Miike', 'Nijirô Murakami, Lily Franky, Ryûnosuke Kamiki, Sôta Fukushi', 'Adventure, Horror, Sci-Fi, Thriller', '2014-11-15', 'A 2nd-year high school student named Shun Takahata lives an ordinary teenage life until one day he\'s suddenly forced to participate in a series of children\'s games such as \"Daruma-san ga Koronda\" with death as the penalty for losing.', 'As-the-Gods-Will-2014', '1Af7IWcOZdfJ', 'fn9r20d4t11f'),
(50, 'Free Guy', 'https://i.postimg.cc/tRtCBVtP/free-guy-2021.webp', 'Shawn Levy', 'Ryan Reynolds, Jodie Comer, Taika Waititi', 'Action, Adventure, Comedy', '2021-08-13', 'A bank teller discovers that he&apos;s actually an NPC inside a brutal, open world video game.', 'free-guy-2021', 'k8EMjWaxeKUu', 'tsejlh17y01e'),
(49, 'Snowden', 'https://i.postimg.cc/cCZNyDVx/snowden.webp', 'Oliver Stone', 'Joseph Gordon-Levitt, Shailene Woodley, Melissa Leo', 'Biography, Drama, Thriller', '2016-09-16', 'SNOWDEN stars Joseph Gordon-Levitt and is written and directed by Oliver Stone. The script is based on the books The Snowden Files: The Inside Story of the World\'s Most Wanted Man by Luke Harding and Time of the Octopus by Anatoly Kucherena.', 'snowden-2016', 'zq4vZK8bY5lk', 'dw2f6zl561ng'),
(48, 'The Imitation Game', 'https://i.postimg.cc/QtskZ1xg/The-Imitation-Game.webp', 'Morten Tyldum', 'Benedict Cumberbatch, Keira Knightley, Matthew Goode', 'Biography, Drama, Thriller', '2014-12-25', 'Based on the real life story of legendary cryptanalyst Alan Turing, the film portrays the nail-biting race against time by Turing and his brilliant team of code-breakers at Britain\'s top-secret Government Code and Cypher School at Bletchley Park, during the darkest days of World War II.', 'The-Imitation-Game', 'QkHOF3mD06lR', 'gh7ho6lft2sz'),
(47, 'Nightbooks', 'https://i.postimg.cc/ZqL17ykq/Nightbooks.webp', 'David Yarovesky', 'Winslow Fegley, Lidya Jewett, Krysten Ritter', 'Family, Fantasy, Horror', '2021-09-15', 'Follows Alex, a boy obsessed with scary stories who is imprisoned by an evil young witch in her contemporary New York City apartment.', 'Nightbooks', '3v6PVPcV2zwW', 'mn6ktpr2xmgo'),
(46, 'Prisoners of the Ghostland', 'https://i.postimg.cc/QNcn0TpZ/Prisoners-of-the-Ghostland.webp', 'Sion Sono', 'Nicolas Cage, Sofia Boutella, Nick Cassavetes', 'Action, Horror, Thriller', '2021-09-17', 'A notorious criminal must break an evil curse in order to rescue an abducted girl who has mysteriously disappeared.', 'Prisoners-of-the-Ghostland', 'J8dtpuWv9ZI9', 'b0cjlqpknxr5'),
(45, 'Straight Outta Nowhere', 'https://i.postimg.cc/yNwSGW0w/Straight-Outta-Nowhere.webp', 'Cecilia Aranovich', 'Jeff Bennett, Jeff Bergman, Marty Grabstein', 'Adventure, Animation, Comedy', '2021-09-14', 'The movie involves Scooby-Doo and his friends finding a strange object in the middle of Nowhere, Kansas, the backwoods hometown of Courage and his owners, Eustace and Muriel Bagge.', 'Straight-Outta-Nowhere', 'dnYaSoVOPk1t', 'sksq8iuljyiu'),
(44, 'Kate', 'https://i.postimg.cc/HWMLN6p4/kate-2021.webp', 'Cedric Nicolas-Troyan', 'Mary Elizabeth Winstead, Woody Harrelson, Miku Patricia Martineau', 'Action, Adventure, Crime', '2021-09-10', 'A female assassin has 24 hours to get vengeance on her murderer before she dies.', 'kate-2021', 'YmUSG9wGhWsZ', 'tr30mxnd10qp'),
(43, 'Malignant', 'https://i.postimg.cc/C5ckXJ0g/malignant-2021.webp', 'James Wan', 'Annabelle Wallis, Maddie Hasson, George Young', 'Crime, Horror, Mystery', '2021-09-10', 'Madison is paralyzed by shocking visions of grisly murders, and her torment worsens as she discovers that these waking dreams are in fact terrifying realities.', 'malignant-2021', 'vRTAm0ppqR1X', 'zpa5odenl9ci'),
(42, 'The Voyeurs', 'https://i.postimg.cc/HLY5YQPP/the-voyeurs.webp', 'Michael Mohan', 'Sydney Sweeney, Justice Smith, Ben Hardy', 'Drama, Mystery, Thriller', '2021-09-10', 'Pippa and Thomas move into their dream apartment, they notice that their windows look directly into the apartment opposite, this will set in motion a chain of events that will lead to disaster.', 'the-voyeurs', 'mtLgn2GygHYM', 'u6kos5c1yhod'),
(41, 'Prey', 'https://i.postimg.cc/Vvkm5Ncw/prey-2021.webp', 'Thomas Sieben', 'David Kross, Hanno Koffler, Maria Ehrich', 'Adventure, Drama, Thriller', '2021-09-10', 'A hiking trip into the wild turns into a desperate bid for survival for five friends on the run from a mysterious shooter.', 'prey-2021', 'ZPORc9CsyqWb', 'nb04rdy4mbo9'),
(40, 'Don\'t Breathe 2', 'https://i.postimg.cc/yYn3fJNm/Dont-Breathe-2.webp', 'Rodo Sayagues', 'Stephen Lang, Madelyn Grace, Brendan Sexton III', 'Horror, Thriller', '2021-08-13', 'The sequel is set in the years following the initial deadly home invasion, where Norman Nordstrom (Stephen Lang) lives in quiet solace until his past sins catch up to him.', 'Dont-Breathe-2', '5HgURi7va4OD', 'tf4td6wlzm7w'),
(39, 'Escape Room: Tournament of Champions', 'https://i.postimg.cc/1RG054mz/Escape-Room-Tournament-of-Champions.webp', 'Adam Robitel', 'Taylor Russell, Logan Miller, Deborah Ann Woll', 'Action, Adventure, Horror', '2021-07-16', 'Six people unwittingly find themselves locked in another series of escape rooms, slowly uncovering what they have in common to survive. Joining forces with two of the original survivors, they soon discover they\'ve all played the game before.', 'Escape-Room-Tournament-of-Champions', 'oVUXZs1SczEi', '0yla6fryp4sf'),
(38, 'John Wick: Chapter 3 - Parabellum', 'https://i.postimg.cc/J731kB25/john-wick-3.webp', 'Chad Stahelski', 'Keanu Reeves, Halle Berry, Ian McShane, Laurence Fishburne', 'Action, Crime, Thriller', '2019-05-15', 'In this third installment of the adrenaline-fueled action franchise, skilled assassin John Wick (Keanu Reeves) returns with a $14 million price tag on his head and an army of bounty-hunting killers on his trail. After killing a member of the shadowy international assassin\'s guild, the High Table, John Wick is excommunicado, but the world\'s most ruthless hit men and women await his every turn.', 'john-wick-3', 'AVbZIFcwZN4x', 'q8cq33v0emmu'),
(37, 'Afterlife of the Party', 'https://i.postimg.cc/KvRkzSB7/Afterlife-of-the-Party.webp', 'Stephen Herek', 'Victoria Justice, Adam Garcia, Midori Francis', 'Comedy, Drama, Fantasy', '2021-09-02', 'A social butterfly who dies during her birthday week is given a second chance to right her wrongs on Earth.', 'Afterlife-of-the-Party', 'LFzI3dfEhXOg', 'ryl9fc82egc8'),
(36, 'Mortal Kombat Legends: Battle of the Realms', 'https://i.postimg.cc/8zCj38Pf/Mortal-Kombat-Legends-Battle-of-the-Realms.webp', 'Ethan Spaulding', 'Ike Amadi, Artt Butler, Jennifer Carpenter', 'Action, Adventure, Animation', '2021-08-31', 'The Earthrealm heroes must journey to Outworld and fight for the survival of their homeland, invaded by the forces of evil warlord Shao Kahn, in the tournament to end all tournaments: the final Mortal Kombat.', 'Mortal-Kombat-Legends-Battle-of-the-Realms', 'K8rxJeKG9b4s', 'ni9sl6zvfulq'),
(35, 'Vacation Friends', 'https://i.postimg.cc/B6dJmy7D/Vacation-Friends.webp', 'Clay Tarver', 'John Cena, Lil Rel Howery, Meredith Hagner', 'Adventure, Comedy', '2021-08-27', 'A couple meets up with another couple while on vacation in Mexico, but their friendship takes an awkward turn when they get back home.', 'Vacation-Friends', 'zH6zUxi3w91o', 'qvvicb9jiipr'),
(34, 'He&#39;s All That', 'https://i.postimg.cc/XJggLSY1/hes-all-that.webp', 'Mark Waters', 'Addison Rae, Tanner Buchanan, Madison Pettis', 'Comedy, Romance', '2021-08-27', 'A teenage girl sets out to give a nebbish classmate the ultimate high school makeover. An updated remake of the 1999 film, \'She\'s All That\'.', 'hes-all-that', 'owugLX5hZsrk', 'v3u5dfafb783'),
(33, 'Cinderella', 'https://i.postimg.cc/BQYfnRdS/cinderella-2021.webp', 'Kay Cannon', 'Nicholas Galitzine, Camila Cabello, Billy Porter', 'Comedy, Fantasy, Family', '2021-09-03', 'A modern movie musical with a bold take on the classic fairy tale. Our ambitious heroine has big dreams and with the help of her fab Godmother, she perseveres to make them come true.', 'cinderella-2021', 'SrwPJpfPkFC7', '2at08fbarz43'),
(32, 'The Witcher: Nightmare of the Wolf', 'https://i.postimg.cc/VvtXsJvf/the-witcher-nightmare-of-the-wolf.webp', 'Kwang Il Han', 'Theo James, Graham McTavish, Mary McDonnell', 'Action, Adventure, Animation', '2021-08-23', 'Escaping from poverty to become a witcher, Vesemir slays monsters for coin and glory, but when a new menace rises, he must face the demons of his past.', 'the-witcher-nightmare-of-the-wolf', 'DEaPiPETwig1', '1lmhbmqadaru'),
(31, 'The Loud House', 'https://i.postimg.cc/RFkXT5n0/The-Loud-House.webp', 'Dave Needham', 'David Tennant, Grey Griffin, Michelle Gomez', 'Adventure, Animation, Comedy', '2021-08-20', 'With his parents and all 10 sisters in tow, Lincoln Loud heads to Scotland and learns that royalty runs in the family in this global musical journey.', 'The-Loud-House', 'fIWXnoWNn2XL', 'ntdo06om3ysq'),
(30, ' Reminiscence', 'https://i.postimg.cc/76M012C7/reminiscence.webp', 'Lisa Joy', 'Hugh Jackman, Rebecca Ferguson, Thandiwe Newton', 'Mystery, Romance, Sci-Fi', '2021-08-20', 'Nick Bannister, a private investigator of the mind, navigates the alluring world of the past when his life is changed by new client Mae. A simple case becomes an obsession after she disappears and he fights to learn the truth about her.', 'reminiscence', '2TDdhe2JZzOf', '0sf7jjrnhg7s'),
(29, 'Demonic', 'https://i.postimg.cc/SxvXcGDH/demonic.webp', 'Neill Blomkamp', 'Andrea Agur, Nathalie Boltt, Terry Chen', 'Horror', '2021-08-20', 'A young woman unleashes terrifying demons when supernatural forces at the root of a decades-old rift between mother and daughter are ruthlessly revealed.', 'demonic', 'RYHSr9AWsFGr', 'fxuzowx6jlrw'),
(28, 'Risen', 'https://i.postimg.cc/y6msPNpj/risen.webp', 'Eddie Arya', 'Terri Purchase, Natalie Rose, Buffy Anne Littaua', 'Sci-Fi, Thriller', '2021-08-20', 'Disaster unfolds when a meteor strikes a small town, turning the environment uninhabitable and killing everything in the surrounding area.', 'risen', 'tPNzb1oEzUlN', 'qrdwi6gkj9hc'),
(27, 'PAW Patrol: The Movie', 'https://i.postimg.cc/0Nmx65LL/paw-patrol-the-movie.webp', 'Andrew Hickson, Cal Brunker', 'Tyler Perry, Ron Pardo, Will Brisbin', 'Adventure, Animation, Comedy', '2021-08-20', 'Ryder and the pups are called to Adventure City to stop Mayor Humdinger from turning the bustling metropolis into a state of chaos.', 'paw-patrol-the-movie', 'vlYQlU8NF2Dr', 'ic291lsicbh2'),
(26, 'Sweet Girl', 'https://i.postimg.cc/gkc9Y2MM/Sweet-Girl.webp', 'Brian Andrew Mendoza', 'Jason Momoa, Isabela Merced, Manuel Garcia-Rulfo', 'Action, Drama, Thriller', '2021-08-20', 'A devastated husband vows to bring justice to the people responsible for his wife&apos;s death while protecting the only family he has left, his daughter.', 'sweet-girl', 'Nu4FcOK94JtT', 'qfa0qg2kt7sf'),
(25, 'Snake Eyes: G.I. Joe Origins', 'https://i.postimg.cc/15J5J2kD/snake-eyes-gi-joe-origins.webp', 'Robert Schwentke', 'Henry Golding, Andrew Koji, Haruka Abe', 'Action, Adventure, Fantasy', '2021-07-23', 'A G.I. Joe spin-off centered around the character of Snake Eyes.', 'snake-eyes-gi-joe-origins', 'ncYfUclxsEQM', 'pey0xkx0fcw3'),
(24, 'All the Bright Places', 'https://i.postimg.cc/mDZ4HzXT/all-the-bright-places.webp', 'Brett Haley', 'Elle Fanning, Alexandra Shipp, Felix Mallard, Keegan-Michael Key', 'Drama, Romance', '2020-02-28', 'The story of Violet Markey and Theodore Finch, who meet and change each other\'s lives forever. As they struggle with the emotional and physical scars of their past, they come together, discovering that even the smallest places and moments can mean something.', 'all-the-bright-places', '8vyhnGe0oUxi', 'z1g6kx0m4t5i'),
(23, 'The Kissing Booth 3', 'https://i.postimg.cc/MpqYJjnV/the-kissing-booth-3.webp', 'Vince Marcello', 'Joey King, Joel Courtney, Jacob Elordi', 'Comedy, Romance', '2021-08-11', 'It\'s the summer before Elle Evans is set to head off to college, and she has a big decision to make.', 'the-kissing-booth-3', 'zr9146FwS3Hk', 's0xondqgsn8n'),
(22, 'The Kissing Booth 2', 'https://i.postimg.cc/XYfpf0C4/the-kissing-booth-2.webp', 'Vince Marcello', 'Joey King, Jacob Elordi, Joel Courtney, Carson White', 'Comedy, Romance', '2020-07-24', 'Elle Evans (Joey King) just had the most romantic summer of her life with her reformed bad-boy boyfriend Noah Flynn (Jacob Elordi). But now Noah\'s off to Harvard, and Elle\'s headed back to high school for her senior year.', 'the-kissing-booth-2', 'vxejQp4uQ2an', 'js9ixa9snscd'),
(21, 'The Kissing Booth', 'https://i.postimg.cc/3x5k0wWt/the-kissing-booth.webp', 'Vince Marcello', 'Joey King, Jacob Elordi, Molly Ringwald', 'Comedy, Romance', '2018-05-11', 'A high school student is forced to confront her secret crush at a kissing booth.', 'the-kissing-booth', '0qHRYd3jquur', 'yy9yxp4z3qjs'),
(20, 'The Suicide Squad', 'https://i.postimg.cc/8PRk33rN/the-suicide-squad-2021.webp', 'James Gunn', 'Margot Robbie, Idris Elba, John Cena', 'Action, Adventure, Comedy', '2021-08-06', 'Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.', 'the-suicide-squad-2021', 'zK2jbhOfCtsI', 'zgrk0mezk8io'),
(19, 'Jungle Cruise', 'https://i.postimg.cc/RV3yCfHR/jungle-cruise.webp', 'Jaume Collet-Serra', 'Dwayne Johnson, Emily Blunt, Edgar Ramírez', 'Action, Adventure, Comedy', '2021-07-30', 'Based on Disneyland\'s theme park ride where a small riverboat takes a group of travelers through a jungle filled with dangerous animals and reptiles but with a supernatural element.', 'jungle-cruise', 'L7xFmViac7I3', 'vfoq2hymh2eu'),
(18, 'F9', 'https://i.postimg.cc/5035DFsm/f9.webp', 'Justin Lin', 'Vin Diesel, Michelle Rodriguez, Jordana Brewster', 'Action, Adventure, Crime', '2021-06-25', 'Cipher enlists the help of Jakob, Dom\'s younger brother to take revenge on Dom and his team.', 'f9', 'id4VoVnH7XrZ', '29756vgl0tqp'),
(17, 'Fear Street: 1666', 'https://i.postimg.cc/FH4TMsWz/fear-street-1666.webp', 'Leigh Janiak', 'Kiana Madeira, Ashley Zukerman, Gillian Jacobs', 'Horror, Mystery', '2021-07-16', 'The origins of Sarah Fier\'s curse are finally revealed as history comes full circle on a night that changes the lives of Shadysiders forever.', 'fear-street-1666', 'AZDc3l73J9yH', 'bv2bngp9kom6	'),
(16, 'Fear Street Part Two: 1978', 'https://i.postimg.cc/Qx56YWqv/fear-street-part-two-1978.webp', 'Leigh Janiak', 'Sadie Sink, Emily Rudd, Ryan Simpkins', 'Drama, Horror, Mystery', '2021-07-09', 'Shadyside, 1978. School\'s out for summer and the activities at Camp Nightwing are about to begin. But when another Shadysider is possessed with the urge to kill, the fun in the sun becomes a gruesome fight for survival.', 'fear-street-part-two-1978', 'tkuLRqcGwkIQ', '4i397f8mqn4i'),
(15, 'Fear Street', 'https://i.postimg.cc/rFk8P5kr/fear-street.webp', 'Leigh Janiak', 'Kiana Madeira, Olivia Scott Welch, Benjamin Flores Jr.', 'Horror, Mystery', '2021-07-02', 'A circle of teenage friends accidentally encounter the ancient evil responsible for a series of brutal murders that have plagued their town for over 300 years. Welcome to Shadyside.', 'fear-street', 'B96sHN0F8S04', 'mvs66yzab8e3'),
(14, 'Space Jam: A New Legacy', 'https://i.postimg.cc/sD8bNSnV/space-jam-a-new-legacy.webp', 'Malcolm D. Lee', 'LeBron James, Don Cheadle, Cedric Joe', 'Adventure, Animation, Comedy', '2021-07-16', 'A rogue artificial intelligence kidnaps the son of famed basketball player LeBron James, who then has to work with Bugs Bunny to win a basketball game.', 'space-jam-a-new-legacy', 'ynmbirEzzkSy', '1llrzaw6696b'),
(13, 'The Forever Purge', 'https://i.postimg.cc/NMpz7r9v/the-forever-purge.webp', 'Everardo Gout', 'Ana de la Reguera, Tenoch Huerta, Josh Lucas', 'Action, Horror, Thriller', '2021-07-09', 'All the rules are broken as a sect of lawless marauders decides that the annual Purge does not stop at daybreak and instead should never end.', 'the-forever-purge', 'UQDGDCL86Mo6', 'imfvimyf25js'),
(12, 'Willy\'s Wonderland', 'https://i.postimg.cc/c1kzvwGQ/willys-wonderland.webp', 'Kevin Lewis', 'Nicolas Cage, Caylee Cowan, Beth Grant, Emily Tosta', 'Horror, Thriller', '2021-02-12', 'A quiet loner (Nic Cage) finds himself stranded in a remote town when his car breaks down. Unable to pay for the repairs he needs, he agrees to spend the night cleaning Willy\'s Wonderland, an abandoned family fun center. But this wonderland has a dark secret that the \"The Janitor\" is about to discover.', 'willys-wonderland', 'hISc2yC1y3Ho', 'n4pb8qtiv1nk'),
(11, 'Black Widow', 'https://i.postimg.cc/D0wRtckz/black-widow-2021.webp', 'Cate Shortland', 'Scarlett Johansson, Florence Pugh, David Harbour', 'Action, Adventure, Sci-Fi', '2021-07-09', 'A film about Natasha Romanoff in her quests between the films Civil War and Infinity War.', 'black-widow-2021', 'kpPYjGT37vEc', 'i6k2dhnm3nch'),
(10, 'Peter Rabit 2: The Runaway', 'https://i.postimg.cc/TPvFRxMF/peter-rabbit-two.webp', 'Will Gluck', 'Rose Byrne, Domhnall Gleeson, David Oyelowo', 'Adventure, Animation, Comedy', '2021-06-11', 'Thomas and Bea are now married and living with Peter and his rabbit family. Bored of life in the garden, Peter goes to the big city, where he meets shady characters and ends up creating chaos for the whole family.', 'peter-rabit-2-the-runaway', '2baD1zf8XGlo', 'kzorqdf0mk40'),
(9, 'Tom and Jerry', 'https://i.postimg.cc/4y02jkQ8/tom-and-jerry.webp', 'Tim Story', 'Chloë Grace Moretz, Michael Peña, Colin Jost, Tom', 'Adventure, Animation, Comedy, Family', '2021-02-11', 'Adaptation of the classic Hanna-Barbera property, which reveals how Tom and Jerry first meet and form their rivalry.', 'tom-and-jerry', 'U7ML849qhs14', '9ndzivuxtyo6'),
(8, 'Godzilla vs. Kong', 'https://i.postimg.cc/sfTk5b7G/godzilla-vs-kingkong.webp', 'Adam Wingard', 'Alexander Skarsgård, Millie Bobby Brown, Rebecca Hall, Brian Tyree Henry', 'Action, Sci-Fi, Thriller', '2021-03-24', 'Legends collide as Godzilla and Kong, the two most powerful forces of nature, clash on the big screen in a spectacular battle for the ages.', 'godzilla-vs-kong', 'rxuleDlv7w1m', 'suw8vezusk5x'),
(7, 'Mortal Kombat', 'https://i.postimg.cc/pLF3bT7K/mortal-kombat-2021.webp', 'Simon McQuoid', 'Lewis Tan, Jessica McNamee, Josh Lawson, Joe Taslim', 'Action, Adventure, Fantasy, Sci-Fi, Thriller', '2021-04-08', 'MMA fighter Cole Young seeks out Earth\'s greatest champions in order to stand against the enemies of Outworld in a high stakes battle for the universe.', 'mortal-kombat', 'TRWjyMBavKXE', '1br664zk37zm'),
(6, 'The Tomorrow War', 'https://i.postimg.cc/qqqZmMyh/the-tomorrow-war.webp', 'Chris McKay', 'Chris Pratt, Yvonne Strahovski, J.K. Simmons', 'Action, Adventure, Sci-Fi', '2021-07-02', 'A family man is drafted to fight in a future war where the fate of humanity relies on his ability to confront the past.', 'the-tomorrow-war', 'Lln3oFTEHhVm', 'ey6glv8dggm0'),
(5, 'Army of the Dead', 'https://i.postimg.cc/MKXh5tmP/army-of-the-dead.webp', 'Zack Snyder', 'Dave Bautista, Ella Purnell, Ana de la Reguera, Omari Hardwick', 'Action, Crime, Horror, Sci-Fi, Thriller', '2021-05-14', 'Following a zombie outbreak in Las Vegas, a group of mercenaries take the ultimate gamble, venturing into the quarantine zone to pull off the greatest heist ever attempted.', 'army-of-the-dead', 'hJZNEh5rNE27', '7tljoc0igqoi'),
(4, 'Cruella', 'https://i.postimg.cc/KjpCFgxD/cruella-2021.webp', 'Craig Gillespie', 'Emma Stone, Emma Thompson, Joel Fry', 'Comedy, Crime', '2021-05-28', 'A live-action prequel feature film following a young Cruella de Vil.', 'cruella', 'bsDXwjmLn7QU', 'enzjh2qy0xzv'),
(3, 'Hitman\'s Wife\'s Bodyguard', 'https://i.postimg.cc/vm7jTKGB/hitman-wifes-bodyguard.webp', 'Patrick Hughes', 'Ryan Reynolds, Samuel L. Jackson, Salma Hayek', 'Action, Comedy, Crime', '2021-06-16', 'The bodyguard Michael Bryce continues his friendship with assassin Darius Kincaid as they try to save Darius\' wife Sonia.', 'hitmans-wifes-bodyguard', 'XdCygrLOJLpL', '0v5t30hydvtw'),
(2, 'A Quiet Place Part II', 'https://i.postimg.cc/LXTrCbW7/a-quiet-place-part-ii.webp', 'John Krasinski', 'Emily Blunt, Millicent Simmonds, Cillian Murphy', 'Drama, Horror, Sci-Fi', '2021-05-28', 'Following the events at home, the Abbott family now face the terrors of the outside world. Forced to venture into the unknown, they realize the creatures that hunt by sound are not the only threats lurking beyond the sand path.', 'a-quiet-place-part-II', 'qIEFTpGDfxaN', 's1hsvb7ofp7u'),
(1, 'The Boss Baby: Family Business', 'https://i.postimg.cc/9MWk7BfB/the-boss-baby-family-business-2021.webp', 'Tom McGrath', 'Alec Baldwin, James Marsden, Amy Sedaris', 'Adventure, Animation, Comedy', '2021-09-17', 'The Templeton brothers have become adults and drifted away from each other, but a new boss baby with a cutting-edge approach is about to bring them together again - and inspire a new family business.', 'the-boss-baby-family-business', 'UezuGZPCYuh7', 'g02q2wm1776r');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `movies-list`
--
ALTER TABLE `movies-list`
  ADD PRIMARY KEY (`movieID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `movies-list`
--
ALTER TABLE `movies-list`
  MODIFY `movieID` int(100) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=79;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
